-- FootGrid core PostgreSQL schema (PostgreSQL 16+ / Aurora PostgreSQL compatible)
--
-- Migration convention: execute this as the initial baseline, then use one
-- forward-only migration per change. Services receive separate DB roles and may
-- write only their owning schema. UUIDs are generated by the application as UUIDv7
-- on writes; gen_random_uuid() is a safe fallback for server-created records.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS competition;
CREATE SCHEMA IF NOT EXISTS match_data;
CREATE SCHEMA IF NOT EXISTS read_model;
CREATE SCHEMA IF NOT EXISTS platform;

CREATE TYPE platform.membership_role AS ENUM (
  'OWNER', 'ADMIN', 'ORGANIZER', 'TEAM_MANAGER', 'SCORER', 'REFEREE',
  'COACH', 'PLAYER', 'PARENT', 'FAN'
);
CREATE TYPE platform.membership_status AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED');
CREATE TYPE platform.record_status AS ENUM ('ACTIVE', 'ARCHIVED');
CREATE TYPE platform.match_status AS ENUM (
  'DRAFT', 'SCHEDULED', 'READY', 'LIVE', 'PAUSED', 'COMPLETED', 'FINALIZED', 'ABANDONED'
);
CREATE TYPE platform.match_side AS ENUM ('HOME', 'AWAY');
CREATE TYPE platform.participation_status AS ENUM ('STARTER', 'BENCH', 'NOT_SELECTED', 'LEFT_MATCH');
CREATE TYPE platform.clock_state AS ENUM ('NOT_STARTED', 'RUNNING', 'PAUSED', 'ENDED');
CREATE TYPE platform.event_state AS ENUM ('CONFIRMED', 'REVERSED');
CREATE TYPE platform.competition_format AS ENUM ('LEAGUE', 'KNOCKOUT', 'HYBRID', 'FRIENDLY_SERIES');
CREATE TYPE platform.competition_status AS ENUM ('DRAFT', 'PUBLISHED', 'COMPLETED', 'ARCHIVED');
CREATE TYPE platform.stage_type AS ENUM ('LEAGUE', 'GROUP', 'KNOCKOUT', 'ROUND_ROBIN');
CREATE TYPE platform.live_session_command AS ENUM ('PAUSE', 'RESUME', 'END_PERIOD', 'START_NEXT_PERIOD', 'END_MATCH');

CREATE OR REPLACE FUNCTION platform.touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = clock_timestamp();
  RETURN NEW;
END;
$$;

-- ============================================================================
-- identity schema — owned by identity service
-- PII is kept here; event/read schemas store profile/participant IDs only.
-- ============================================================================

CREATE TABLE identity.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(120) NOT NULL CHECK (char_length(btrim(name)) >= 2),
  slug citext NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]{3,80}$'),
  timezone varchar(64) NOT NULL,
  logo_object_key varchar(512),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TRIGGER organizations_touch BEFORE UPDATE ON identity.organizations
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE identity.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cognito_subject uuid NOT NULL UNIQUE,
  display_name varchar(100) NOT NULL CHECK (char_length(btrim(display_name)) >= 1),
  email_ciphertext bytea,
  phone_ciphertext bytea,
  -- HMAC-SHA256 normalized E.164 phone using an app-held pepper. Never a raw phone index.
  phone_lookup_hash bytea UNIQUE,
  avatar_object_key varchar(512),
  status platform.record_status NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (phone_lookup_hash IS NULL OR octet_length(phone_lookup_hash) = 32)
);
CREATE TRIGGER users_touch BEFORE UPDATE ON identity.users
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE identity.organization_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES identity.organizations(id),
  user_id uuid REFERENCES identity.users(id),
  invited_email_ciphertext bytea,
  invited_phone_ciphertext bytea,
  invited_contact_hash bytea,
  role platform.membership_role NOT NULL,
  status platform.membership_status NOT NULL DEFAULT 'INVITED',
  invited_by_user_id uuid REFERENCES identity.users(id),
  accepted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (user_id IS NOT NULL OR invited_contact_hash IS NOT NULL),
  CHECK (status <> 'ACTIVE' OR user_id IS NOT NULL)
);
CREATE UNIQUE INDEX organization_memberships_active_user_uq
  ON identity.organization_memberships (organization_id, user_id)
  WHERE user_id IS NOT NULL AND status <> 'REMOVED';
CREATE INDEX organization_memberships_org_role_ix
  ON identity.organization_memberships (organization_id, role)
  WHERE status = 'ACTIVE';
CREATE TRIGGER organization_memberships_touch BEFORE UPDATE ON identity.organization_memberships
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE identity.player_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES identity.organizations(id),
  user_id uuid REFERENCES identity.users(id),
  display_name varchar(100) NOT NULL CHECK (char_length(btrim(display_name)) >= 1),
  phone_ciphertext bytea,
  phone_lookup_hash bytea,
  preferred_positions varchar(16)[] NOT NULL DEFAULT '{}',
  avatar_object_key varchar(512),
  status platform.record_status NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (cardinality(preferred_positions) <= 4),
  CHECK (phone_lookup_hash IS NULL OR octet_length(phone_lookup_hash) = 32)
);
CREATE UNIQUE INDEX player_profiles_org_phone_uq
  ON identity.player_profiles (organization_id, phone_lookup_hash)
  WHERE phone_lookup_hash IS NOT NULL AND status = 'ACTIVE';
CREATE INDEX player_profiles_org_display_name_ix
  ON identity.player_profiles (organization_id, lower(display_name), id)
  WHERE status = 'ACTIVE';
CREATE TRIGGER player_profiles_touch BEFORE UPDATE ON identity.player_profiles
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

-- ============================================================================
-- competition schema — owned by competition service.
-- External ID columns intentionally have no cross-service foreign key.
-- ============================================================================

CREATE TABLE competition.venues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name varchar(120) NOT NULL CHECK (char_length(btrim(name)) >= 2),
  address varchar(500),
  timezone varchar(64) NOT NULL,
  latitude numeric(8,5),
  longitude numeric(8,5),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);
CREATE UNIQUE INDEX venues_org_name_uq ON competition.venues (organization_id, lower(name));
CREATE TRIGGER venues_touch BEFORE UPDATE ON competition.venues
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE competition.teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name varchar(100) NOT NULL CHECK (char_length(btrim(name)) >= 2),
  short_name varchar(20),
  badge_object_key varchar(512),
  primary_color char(7) CHECK (primary_color IS NULL OR primary_color ~ '^#[0-9A-Fa-f]{6}$'),
  status platform.record_status NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE UNIQUE INDEX teams_org_name_uq ON competition.teams (organization_id, lower(name))
  WHERE status = 'ACTIVE';
CREATE TRIGGER teams_touch BEFORE UPDATE ON competition.teams
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE competition.team_memberships (
  team_id uuid NOT NULL REFERENCES competition.teams(id) ON DELETE CASCADE,
  player_id uuid NOT NULL, -- identity.player_profiles.id
  default_shirt_number smallint CHECK (default_shirt_number BETWEEN 1 AND 99),
  default_position_code varchar(16),
  status platform.record_status NOT NULL DEFAULT 'ACTIVE',
  joined_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  left_at timestamptz,
  PRIMARY KEY (team_id, player_id),
  CHECK (left_at IS NULL OR left_at >= joined_at)
);
CREATE UNIQUE INDEX team_memberships_active_shirt_uq
  ON competition.team_memberships (team_id, default_shirt_number)
  WHERE status = 'ACTIVE' AND default_shirt_number IS NOT NULL;

CREATE TABLE competition.competitions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name varchar(160) NOT NULL CHECK (char_length(btrim(name)) >= 2),
  format platform.competition_format NOT NULL,
  timezone varchar(64) NOT NULL,
  points_for_win smallint NOT NULL DEFAULT 3 CHECK (points_for_win >= 0),
  points_for_draw smallint NOT NULL DEFAULT 1 CHECK (points_for_draw >= 0),
  points_for_loss smallint NOT NULL DEFAULT 0 CHECK (points_for_loss >= 0),
  status platform.competition_status NOT NULL DEFAULT 'DRAFT',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX competitions_org_status_ix ON competition.competitions (organization_id, status, created_at DESC);
CREATE TRIGGER competitions_touch BEFORE UPDATE ON competition.competitions
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE competition.stages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid NOT NULL REFERENCES competition.competitions(id) ON DELETE CASCADE,
  name varchar(120) NOT NULL,
  stage_type platform.stage_type NOT NULL,
  ordinal smallint NOT NULL CHECK (ordinal > 0),
  configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (competition_id, ordinal),
  CHECK (jsonb_typeof(configuration) = 'object')
);

CREATE TABLE competition.competition_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid NOT NULL REFERENCES competition.competitions(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES competition.teams(id),
  seed smallint CHECK (seed > 0),
  group_code varchar(24),
  status platform.record_status NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (competition_id, team_id),
  UNIQUE NULLS NOT DISTINCT (competition_id, seed)
);

-- One row per planned fixture. The Match service owns mutable match/live data;
-- the FK is deliberately absent because service databases can later be split.
CREATE TABLE competition.fixtures (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid NOT NULL REFERENCES competition.competitions(id) ON DELETE CASCADE,
  stage_id uuid REFERENCES competition.stages(id),
  home_entry_id uuid REFERENCES competition.competition_entries(id),
  away_entry_id uuid REFERENCES competition.competition_entries(id),
  match_id uuid UNIQUE, -- match_data.matches.id
  round_label varchar(50),
  scheduled_start_at timestamptz,
  venue_id uuid REFERENCES competition.venues(id),
  status platform.match_status NOT NULL DEFAULT 'SCHEDULED',
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (home_entry_id IS NULL OR home_entry_id <> away_entry_id)
);
CREATE INDEX fixtures_competition_schedule_ix ON competition.fixtures (competition_id, scheduled_start_at, id);
CREATE TRIGGER fixtures_touch BEFORE UPDATE ON competition.fixtures
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

-- ============================================================================
-- match_data schema — owned by Match service. This is the command-side ledger.
-- ============================================================================

CREATE TABLE match_data.matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  competition_id uuid, -- competition.competitions.id, nullable for casual games
  fixture_id uuid UNIQUE, -- competition.fixtures.id, nullable for casual games
  venue_id uuid, -- competition.venues.id
  venue_name_snapshot varchar(120),
  scheduled_start_at timestamptz,
  timezone varchar(64) NOT NULL DEFAULT 'Asia/Kolkata',
  format_code varchar(16) NOT NULL CHECK (format_code IN ('5V5', '6V6', '8V8', '11V11', 'CUSTOM')),
  players_per_side smallint NOT NULL CHECK (players_per_side BETWEEN 2 AND 11),
  period_count smallint NOT NULL CHECK (period_count BETWEEN 1 AND 4),
  total_duration_seconds integer NOT NULL CHECK (total_duration_seconds BETWEEN 600 AND 10800),
  substitutions_allowed smallint CHECK (substitutions_allowed >= 0),
  status platform.match_status NOT NULL DEFAULT 'DRAFT',
  status_version integer NOT NULL DEFAULT 0 CHECK (status_version >= 0),
  created_by_member_id uuid NOT NULL, -- identity.organization_memberships.id
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  finalized_at timestamptz,
  CHECK ((format_code = '5V5' AND players_per_side = 5)
      OR (format_code = '6V6' AND players_per_side = 6)
      OR (format_code = '8V8' AND players_per_side = 8)
      OR (format_code = '11V11' AND players_per_side = 11)
      OR format_code = 'CUSTOM')
);
CREATE INDEX matches_org_schedule_ix ON match_data.matches (organization_id, scheduled_start_at DESC, id);
CREATE INDEX matches_competition_ix ON match_data.matches (competition_id, scheduled_start_at) WHERE competition_id IS NOT NULL;
CREATE INDEX matches_live_ix ON match_data.matches (organization_id, updated_at DESC) WHERE status IN ('LIVE', 'PAUSED');
CREATE TRIGGER matches_touch BEFORE UPDATE ON match_data.matches
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE match_data.match_sides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL REFERENCES match_data.matches(id) ON DELETE CASCADE,
  side platform.match_side NOT NULL,
  team_id uuid, -- competition.teams.id
  display_name varchar(100) NOT NULL CHECK (char_length(btrim(display_name)) >= 1),
  badge_object_key varchar(512),
  color char(7) CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (match_id, side),
  UNIQUE (id, match_id)
);

-- `player_id` may be null for an unknown opponent. A participant is always a
-- match-scoped identity, so anonymous #9 can receive the flip-side of a duel.
CREATE TABLE match_data.match_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL REFERENCES match_data.matches(id) ON DELETE CASCADE,
  match_side_id uuid NOT NULL REFERENCES match_data.match_sides(id) ON DELETE CASCADE,
  player_id uuid, -- identity.player_profiles.id, nullable by design
  shirt_number smallint NOT NULL CHECK (shirt_number BETWEEN 1 AND 99),
  display_name_snapshot varchar(100) NOT NULL CHECK (char_length(btrim(display_name_snapshot)) >= 1),
  position_code varchar(16),
  participation_status platform.participation_status NOT NULL DEFAULT 'NOT_SELECTED',
  pitch_slot varchar(32),
  joined_sequence integer NOT NULL DEFAULT 0 CHECK (joined_sequence >= 0),
  left_sequence integer CHECK (left_sequence IS NULL OR left_sequence >= joined_sequence),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (id, match_id),
  FOREIGN KEY (match_side_id, match_id) REFERENCES match_data.match_sides(id, match_id)
);
CREATE UNIQUE INDEX match_participants_shirt_uq
  ON match_data.match_participants (match_side_id, shirt_number)
  WHERE participation_status <> 'LEFT_MATCH';
CREATE INDEX match_participants_match_side_ix ON match_data.match_participants (match_id, match_side_id, participation_status);
CREATE INDEX match_participants_player_ix ON match_data.match_participants (player_id, match_id) WHERE player_id IS NOT NULL;
CREATE TRIGGER match_participants_touch BEFORE UPDATE ON match_data.match_participants
  FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

-- Exactly one row per match: locked by the command handler before allocating
-- event sequence. Scores are command-side aggregates that are updated only in
-- the same transaction as a valid ledger event, never directly by a UI.
CREATE TABLE match_data.match_live_state (
  match_id uuid PRIMARY KEY REFERENCES match_data.matches(id) ON DELETE CASCADE,
  current_sequence integer NOT NULL DEFAULT 0 CHECK (current_sequence >= 0),
  home_score smallint NOT NULL DEFAULT 0 CHECK (home_score >= 0),
  away_score smallint NOT NULL DEFAULT 0 CHECK (away_score >= 0),
  current_period_number smallint CHECK (current_period_number BETWEEN 1 AND 4),
  elapsed_seconds integer NOT NULL DEFAULT 0 CHECK (elapsed_seconds >= 0),
  clock_state platform.clock_state NOT NULL DEFAULT 'NOT_STARTED',
  active_scorer_member_id uuid,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE match_data.live_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL REFERENCES match_data.matches(id) ON DELETE CASCADE,
  started_by_member_id uuid NOT NULL,
  active_scorer_member_id uuid,
  status platform.clock_state NOT NULL DEFAULT 'RUNNING',
  period_number smallint NOT NULL DEFAULT 1 CHECK (period_number BETWEEN 1 AND 4),
  started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  paused_at timestamptz,
  ended_at timestamptz,
  accumulated_pause_seconds integer NOT NULL DEFAULT 0 CHECK (accumulated_pause_seconds >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK ((status <> 'ENDED') OR ended_at IS NOT NULL)
);
CREATE UNIQUE INDEX live_sessions_one_open_uq ON match_data.live_sessions (match_id) WHERE status <> 'ENDED';

-- Taxonomy is versioned. `qualifier_schema` is a JSON Schema fragment validated
-- in Go; DB keeps it immutable once events reference that (code, version).
CREATE TABLE match_data.action_catalog (
  code varchar(64) NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  display_label varchar(100) NOT NULL,
  allowed_positions varchar(16)[] NOT NULL DEFAULT '{}',
  required_subject_roles varchar(24)[] NOT NULL DEFAULT ARRAY['PRIMARY'],
  score_delta smallint NOT NULL DEFAULT 0 CHECK (score_delta BETWEEN -1 AND 1),
  qualifier_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  stats_mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (code, version),
  CHECK (jsonb_typeof(qualifier_schema) = 'object'),
  CHECK (jsonb_typeof(stats_mapping) = 'object')
);
CREATE UNIQUE INDEX action_catalog_active_code_uq ON match_data.action_catalog (code) WHERE is_active;

-- Baseline vocabulary for the action pickers in match-logger.html and
-- pitch-logger.html. Product changes add a new version instead of updating a
-- referenced record. `ALL` lets the service include an action for every role.
INSERT INTO match_data.action_catalog
  (code, version, display_label, allowed_positions, required_subject_roles, score_delta, qualifier_schema, stats_mapping)
VALUES
  ('GOAL', 1, 'Goal', ARRAY['ALL'], ARRAY['SCORER'], 1,
   '{"type":"object","properties":{"finish_type":{"enum":["STRONG_FOOT","WEAK_FOOT","HEADER","VOLLEY","OTHER"]}}}'::jsonb,
   '{"goals":1}'::jsonb),
  ('ASSIST', 1, 'Assist', ARRAY['MID','ATT','ST','LW','RW','CAM','CM','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"assists":1}'::jsonb),
  ('SHOT_ON_TARGET', 1, 'Shot on target', ARRAY['MID','ATT','ST','LW','RW','CAM','CM'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"shots_on_target":1}'::jsonb),
  ('SHOT_OFF_TARGET', 1, 'Shot off target', ARRAY['MID','ATT','ST','LW','RW','CAM','CM'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"shots_off_target":1}'::jsonb),
  ('SHOT_OFF_POST', 1, 'Off the post', ARRAY['MID','ATT','ST','LW','RW','CAM','CM'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"shots_off_post":1}'::jsonb),
  ('CHANCE_CREATED', 1, 'Chance created', ARRAY['DEF','MID','ATT','ST','LW','RW','CAM','CM','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"chances_created":1}'::jsonb),
  ('KEY_PASS', 1, 'Key pass', ARRAY['MID','CAM','CM','CDM'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"key_passes":1}'::jsonb),
  ('CROSS', 1, 'Cross', ARRAY['LW','RW','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"crosses":1}'::jsonb),
  ('DRIBBLE_WON', 1, 'Beat his man', ARRAY['MID','ATT','ST','LW','RW','CAM','CM'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"dribbles_won":1}'::jsonb),
  ('DUEL_WON', 1, 'Duel won', ARRAY['DEF','MID','CDM','CB','LB','RB'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"duels_won":1}'::jsonb),
  ('DUEL_LOST', 1, 'Duel lost', ARRAY['DEF','MID','CDM','CB','LB','RB'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"duels_lost":1}'::jsonb),
  ('AERIAL_WON', 1, 'Aerial won', ARRAY['DEF','MID','ATT','ST','CB'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"aerials_won":1}'::jsonb),
  ('AERIAL_LOST', 1, 'Aerial lost', ARRAY['DEF','MID','ATT','ST','CB'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"aerials_lost":1}'::jsonb),
  ('TACKLE_WON', 1, 'Tackle won', ARRAY['DEF','MID','CDM','CM','LB','RB'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"tackles_won":1}'::jsonb),
  ('INTERCEPTION', 1, 'Interception', ARRAY['DEF','MID','CDM','CM','CB','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"interceptions":1}'::jsonb),
  ('RECOVERY', 1, 'Recovery', ARRAY['DEF','MID','CDM','CM','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"recoveries":1}'::jsonb),
  ('CLEARANCE', 1, 'Clearance', ARRAY['DEF','CB','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"clearances":1}'::jsonb),
  ('BLOCK', 1, 'Block', ARRAY['DEF','MID','CDM','CB','LB','RB'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"blocks":1}'::jsonb),
  ('DRIBBLED_PAST', 1, 'Dribbled past', ARRAY['DEF','MID','CDM','CB','LB','RB'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"dribbled_past":1}'::jsonb),
  ('LOST_BALL', 1, 'Lost the ball', ARRAY['MID','ATT','ST','LW','RW','CAM','CM'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"lost_balls":1}'::jsonb),
  ('FOUL_COMMITTED', 1, 'Foul', ARRAY['ALL'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"fouls_committed":1}'::jsonb),
  ('FOUL_WON', 1, 'Fouled', ARRAY['ALL'], ARRAY['PRIMARY','OPPONENT'], 0, '{}'::jsonb, '{"fouls_won":1}'::jsonb),
  ('GOALKEEPER_SAVE', 1, 'Save', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"saves":1}'::jsonb),
  ('GOALKEEPER_DIVING_SAVE', 1, 'Diving save', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"diving_saves":1}'::jsonb),
  ('GOALKEEPER_CLAIM', 1, 'Claim', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"claims":1}'::jsonb),
  ('GOALKEEPER_PUNCH', 1, 'Punch', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"punches":1}'::jsonb),
  ('GOALKEEPER_SWEEP', 1, 'Sweep', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"sweeps":1}'::jsonb),
  ('GOAL_CONCEDED', 1, 'Goal conceded', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"goals_conceded":1}'::jsonb),
  ('DISTRIBUTION_LONG', 1, 'Long kick', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"long_distributions":1}'::jsonb),
  ('DISTRIBUTION_SHORT', 1, 'Short distribution', ARRAY['GK'], ARRAY['PRIMARY'], 0, '{}'::jsonb, '{"short_distributions":1}'::jsonb),
  ('SUBSTITUTION', 1, 'Substitution', ARRAY['ALL'], ARRAY['PLAYER_ON','PLAYER_OFF'], 0, '{}'::jsonb, '{}'::jsonb),
  ('SCORE_ADJUSTMENT', 1, 'Score adjustment', ARRAY['ALL'], ARRAY['PRIMARY'], 0,
   '{"type":"object","required":["reason"],"properties":{"reason":{"type":"string"},"score_delta":{"enum":[-1,1]}}}'::jsonb,
   '{}'::jsonb),
  ('EVENT_REVERSAL', 1, 'Event reversal', ARRAY['ALL'], ARRAY['PRIMARY'], 0,
   '{"type":"object","required":["reason"]}'::jsonb, '{}'::jsonb)
ON CONFLICT (code, version) DO NOTHING;

CREATE TABLE match_data.match_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL REFERENCES match_data.matches(id) ON DELETE RESTRICT,
  client_event_id uuid NOT NULL,
  sequence integer NOT NULL CHECK (sequence > 0),
  action_code varchar(64) NOT NULL,
  action_catalog_version integer NOT NULL,
  side platform.match_side NOT NULL,
  period_number smallint NOT NULL CHECK (period_number BETWEEN 1 AND 4),
  match_elapsed_seconds integer NOT NULL CHECK (match_elapsed_seconds >= 0),
  client_occurred_at timestamptz,
  recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  recorded_by_member_id uuid NOT NULL,
  qualifiers jsonb NOT NULL DEFAULT '{}'::jsonb,
  state platform.event_state NOT NULL DEFAULT 'CONFIRMED',
  source varchar(16) NOT NULL DEFAULT 'LOGGER' CHECK (source IN ('LOGGER', 'OFFLINE_SYNC', 'ADMIN', 'SYSTEM')),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (match_id, sequence),
  UNIQUE (match_id, client_event_id),
  UNIQUE (id, match_id),
  FOREIGN KEY (action_code, action_catalog_version)
    REFERENCES match_data.action_catalog(code, version),
  CHECK (jsonb_typeof(qualifiers) = 'object')
);
CREATE INDEX match_events_match_sequence_ix ON match_data.match_events (match_id, sequence);
CREATE INDEX match_events_match_time_ix ON match_data.match_events (match_id, match_elapsed_seconds, sequence);
CREATE INDEX match_events_action_ix ON match_data.match_events (action_code, recorded_at DESC);

CREATE TABLE match_data.match_event_subjects (
  match_id uuid NOT NULL,
  event_id uuid NOT NULL REFERENCES match_data.match_events(id) ON DELETE CASCADE,
  participant_id uuid NOT NULL,
  role varchar(24) NOT NULL CHECK (role IN (
    'PRIMARY', 'SCORER', 'ASSISTER', 'OPPONENT', 'GOALKEEPER', 'PLAYER_ON', 'PLAYER_OFF', 'CARD_RECIPIENT'
  )),
  ordinal smallint NOT NULL DEFAULT 1 CHECK (ordinal > 0),
  PRIMARY KEY (event_id, role, ordinal),
  FOREIGN KEY (event_id, match_id) REFERENCES match_data.match_events(id, match_id) ON DELETE CASCADE,
  FOREIGN KEY (participant_id, match_id) REFERENCES match_data.match_participants(id, match_id)
);
CREATE INDEX match_event_subjects_participant_ix ON match_data.match_event_subjects (participant_id, event_id);

-- This linking record is the only marker that an event has been undone. The
-- reversed event continues to exist unchanged; all projections exclude it.
CREATE TABLE match_data.event_reversals (
  reversal_event_id uuid PRIMARY KEY REFERENCES match_data.match_events(id) ON DELETE RESTRICT,
  reversed_event_id uuid NOT NULL REFERENCES match_data.match_events(id) ON DELETE RESTRICT,
  reason varchar(500) NOT NULL CHECK (char_length(btrim(reason)) >= 3),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (reversed_event_id),
  CHECK (reversal_event_id <> reversed_event_id)
);

CREATE OR REPLACE FUNCTION match_data.validate_event_reversal()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  reversal_match uuid;
  reversed_match uuid;
  reversal_action varchar(64);
BEGIN
  SELECT match_id, action_code INTO reversal_match, reversal_action
  FROM match_data.match_events WHERE id = NEW.reversal_event_id;
  SELECT match_id INTO reversed_match FROM match_data.match_events WHERE id = NEW.reversed_event_id;
  IF reversal_match IS DISTINCT FROM reversed_match THEN
    RAISE EXCEPTION 'reversal and reversed event must belong to the same match';
  END IF;
  IF reversal_action <> 'EVENT_REVERSAL' THEN
    RAISE EXCEPTION 'reversal event action must be EVENT_REVERSAL';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER event_reversals_validate BEFORE INSERT ON match_data.event_reversals
  FOR EACH ROW EXECUTE FUNCTION match_data.validate_event_reversal();

-- ============================================================================
-- platform schema — cross-cutting reliability/audit data.
-- The outbox record is inserted in the same transaction as a match event.
-- ============================================================================

CREATE TABLE platform.idempotency_records (
  scope varchar(160) NOT NULL, -- e.g. user UUID + route name
  idempotency_key varchar(128) NOT NULL,
  request_fingerprint bytea NOT NULL,
  response_status smallint NOT NULL CHECK (response_status BETWEEN 100 AND 599),
  response_body jsonb NOT NULL,
  resource_id uuid,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (scope, idempotency_key),
  CHECK (expires_at > created_at)
);
CREATE INDEX idempotency_records_expiry_ix ON platform.idempotency_records (expires_at);

CREATE TABLE platform.outbox_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  aggregate_type varchar(64) NOT NULL,
  aggregate_id uuid NOT NULL,
  aggregate_sequence integer,
  event_type varchar(128) NOT NULL,
  payload jsonb NOT NULL,
  trace_id varchar(64),
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  published_at timestamptz,
  publish_attempts integer NOT NULL DEFAULT 0 CHECK (publish_attempts >= 0),
  locked_until timestamptz,
  last_error varchar(1000),
  CHECK (jsonb_typeof(payload) = 'object')
);
CREATE INDEX outbox_unpublished_ix ON platform.outbox_events (occurred_at, id)
  WHERE published_at IS NULL;

CREATE TABLE platform.audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  actor_user_id uuid,
  actor_member_id uuid,
  action varchar(100) NOT NULL,
  resource_type varchar(64) NOT NULL,
  resource_id uuid NOT NULL,
  before_state jsonb,
  after_state jsonb,
  request_id varchar(64),
  ip inet,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX audit_log_resource_ix ON platform.audit_log (resource_type, resource_id, occurred_at DESC);
CREATE INDEX audit_log_org_time_ix ON platform.audit_log (organization_id, occurred_at DESC);

-- ============================================================================
-- read_model schema — owned by projection service. Rebuildable from ledger.
-- ============================================================================

CREATE TABLE read_model.consumer_inbox (
  consumer_name varchar(100) NOT NULL,
  source_event_id uuid NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (consumer_name, source_event_id)
);

CREATE TABLE read_model.match_snapshots (
  match_id uuid PRIMARY KEY,
  organization_id uuid NOT NULL,
  status platform.match_status NOT NULL,
  home_name varchar(100) NOT NULL,
  away_name varchar(100) NOT NULL,
  home_score smallint NOT NULL CHECK (home_score >= 0),
  away_score smallint NOT NULL CHECK (away_score >= 0),
  current_period_number smallint,
  elapsed_seconds integer NOT NULL DEFAULT 0,
  last_event_sequence integer NOT NULL DEFAULT 0,
  generated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX match_snapshots_org_status_ix ON read_model.match_snapshots (organization_id, status, generated_at DESC);

CREATE TABLE read_model.match_timeline_entries (
  match_id uuid NOT NULL,
  event_id uuid NOT NULL,
  sequence integer NOT NULL,
  minute smallint NOT NULL CHECK (minute >= 0),
  side platform.match_side NOT NULL,
  action_code varchar(64) NOT NULL,
  action_label varchar(100) NOT NULL,
  actor_display_name varchar(100),
  is_public boolean NOT NULL DEFAULT true,
  is_reversed boolean NOT NULL DEFAULT false,
  generated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (match_id, event_id),
  UNIQUE (match_id, sequence)
);
CREATE INDEX match_timeline_public_ix ON read_model.match_timeline_entries (match_id, sequence DESC)
  WHERE is_public AND NOT is_reversed;

CREATE TABLE read_model.player_match_stat_lines (
  match_id uuid NOT NULL,
  participant_id uuid NOT NULL,
  player_id uuid,
  side platform.match_side NOT NULL,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_event_sequence integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (match_id, participant_id),
  CHECK (jsonb_typeof(metrics) = 'object')
);
CREATE INDEX player_match_stat_lines_player_ix ON read_model.player_match_stat_lines (player_id, updated_at DESC)
  WHERE player_id IS NOT NULL;

CREATE TABLE read_model.team_match_stat_lines (
  match_id uuid NOT NULL,
  side platform.match_side NOT NULL,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_event_sequence integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (match_id, side),
  CHECK (jsonb_typeof(metrics) = 'object')
);

CREATE TABLE read_model.competition_standing_rows (
  competition_id uuid NOT NULL,
  stage_id uuid,
  team_id uuid NOT NULL,
  rank smallint NOT NULL CHECK (rank > 0),
  played smallint NOT NULL DEFAULT 0 CHECK (played >= 0),
  won smallint NOT NULL DEFAULT 0 CHECK (won >= 0),
  drawn smallint NOT NULL DEFAULT 0 CHECK (drawn >= 0),
  lost smallint NOT NULL DEFAULT 0 CHECK (lost >= 0),
  goals_for smallint NOT NULL DEFAULT 0 CHECK (goals_for >= 0),
  goals_against smallint NOT NULL DEFAULT 0 CHECK (goals_against >= 0),
  points smallint NOT NULL DEFAULT 0 CHECK (points >= 0),
  calculated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (competition_id, stage_id, team_id),
  UNIQUE NULLS NOT DISTINCT (competition_id, stage_id, rank)
);
CREATE INDEX competition_standing_rows_sort_ix
  ON read_model.competition_standing_rows (competition_id, stage_id, rank);

-- Recommended grants (roles are created by infrastructure, not this migration):
-- GRANT USAGE ON SCHEMA identity TO identity_service;
-- GRANT ALL ON ALL TABLES IN SCHEMA identity TO identity_service;
-- GRANT USAGE ON SCHEMA competition TO competition_service;
-- GRANT ALL ON ALL TABLES IN SCHEMA competition TO competition_service;
-- GRANT USAGE ON SCHEMA match_data TO match_service;
-- GRANT ALL ON ALL TABLES IN SCHEMA match_data TO match_service;
-- GRANT USAGE ON SCHEMA read_model TO projection_service;
-- GRANT ALL ON ALL TABLES IN SCHEMA read_model TO projection_service;
-- GRANT USAGE ON SCHEMA platform TO match_service, projection_service, identity_service, competition_service;
